title: "2023 研究資料管理工作坊"
description: ""
baseurl: ""
url: "https://depositar.github.io"

theme: jekyll-nagymaros

copyright: false
indexing: true
permalink: pretty
exclude:
  - demo/
  - jekyll-nagymaros.gemspec
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-sitemap

sass:
  sourcemap: never
